version: 2.1
description: Automatically build and push to your GitHub Repo Wiki

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Push Wiki To Project Wiki
          command: |
            git config user.email "gommzy@gmx.de"
            git config user.name "gommzystudio"
            git remote remove origin
            git remote add origin https://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@github.com/gommzystudio/lymmzy_wiki > /dev/null 2>&1
            git push origin master > /dev/null 2>&1

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
